/*
* Copyright (c) 2025-present Henri Michelon
*
* This software is released under the MIT License.
* https://opensource.org/licenses/MIT
*/
module;
extern "C"
{
    #define LUA_LIB
    #include "lua.h"
}
module vireo.lua;

import std;

namespace vireo {

    void LuaBindings::_register(lua_State* L) {
        luabridge::getGlobalNamespace(L).beginNamespace("vireo")
            // Backend
            .beginNamespace("Backend")
                .addProperty("UNDEFINED", []{ return (int)Backend::UNDEFINED; })
                .addProperty("DIRECTX",   []{ return (int)Backend::DIRECTX; })
                .addProperty("VULKAN",    []{ return (int)Backend::VULKAN; })
            .endNamespace()
            // Filter
            .beginNamespace("Filter")
                .addProperty("NEAREST", []{ return (int)Filter::NEAREST; })
                .addProperty("LINEAR",  []{ return (int)Filter::LINEAR; })
            .endNamespace()
            // AddressMode
            .beginNamespace("AddressMode")
                .addProperty("REPEAT",          []{ return (int)AddressMode::REPEAT; })
                .addProperty("MIRRORED_REPEAT", []{ return (int)AddressMode::MIRRORED_REPEAT; })
                .addProperty("CLAMP_TO_EDGE",   []{ return (int)AddressMode::CLAMP_TO_EDGE; })
                .addProperty("CLAMP_TO_BORDER", []{ return (int)AddressMode::CLAMP_TO_BORDER; })
            .endNamespace()
            // MipMapMode
            .beginNamespace("MipMapMode")
                .addProperty("NEAREST", []{ return (int)MipMapMode::NEAREST; })
                .addProperty("LINEAR",  []{ return (int)MipMapMode::LINEAR; })
            .endNamespace()
            .beginNamespace("ImageFormat")
                .addProperty("R8_UNORM",               []{ return (int)ImageFormat::R8_UNORM; })
                .addProperty("R8_SNORM",               []{ return (int)ImageFormat::R8_SNORM; })
                .addProperty("R8_UINT",                []{ return (int)ImageFormat::R8_UINT; })
                .addProperty("R8_SINT",                []{ return (int)ImageFormat::R8_SINT; })

                .addProperty("R8G8_UNORM",             []{ return (int)ImageFormat::R8G8_UNORM; })
                .addProperty("R8G8_SNORM",             []{ return (int)ImageFormat::R8G8_SNORM; })
                .addProperty("R8G8_UINT",              []{ return (int)ImageFormat::R8G8_UINT; })
                .addProperty("R8G8_SINT",              []{ return (int)ImageFormat::R8G8_SINT; })

                .addProperty("R8G8B8A8_UNORM",         []{ return (int)ImageFormat::R8G8B8A8_UNORM; })
                .addProperty("R8G8B8A8_SNORM",         []{ return (int)ImageFormat::R8G8B8A8_SNORM; })
                .addProperty("R8G8B8A8_UINT",          []{ return (int)ImageFormat::R8G8B8A8_UINT; })
                .addProperty("R8G8B8A8_SINT",          []{ return (int)ImageFormat::R8G8B8A8_SINT; })
                .addProperty("R8G8B8A8_SRGB",          []{ return (int)ImageFormat::R8G8B8A8_SRGB; })

                .addProperty("B8G8R8A8_UNORM",         []{ return (int)ImageFormat::B8G8R8A8_UNORM; })
                .addProperty("B8G8R8A8_SRGB",          []{ return (int)ImageFormat::B8G8R8A8_SRGB; })
                .addProperty("B8G8R8X8_UNORM",         []{ return (int)ImageFormat::B8G8R8X8_UNORM; })
                .addProperty("B8G8R8X8_SRGB",          []{ return (int)ImageFormat::B8G8R8X8_SRGB; })

                .addProperty("A2B10G10R10_UNORM",      []{ return (int)ImageFormat::A2B10G10R10_UNORM; })
                .addProperty("A2B10G10R10_UINT",       []{ return (int)ImageFormat::A2B10G10R10_UINT; })

                .addProperty("R16_UNORM",              []{ return (int)ImageFormat::R16_UNORM; })
                .addProperty("R16_SNORM",              []{ return (int)ImageFormat::R16_SNORM; })
                .addProperty("R16_UINT",               []{ return (int)ImageFormat::R16_UINT; })
                .addProperty("R16_SINT",               []{ return (int)ImageFormat::R16_SINT; })
                .addProperty("R16_SFLOAT",             []{ return (int)ImageFormat::R16_SFLOAT; })

                .addProperty("R16G16_UNORM",           []{ return (int)ImageFormat::R16G16_UNORM; })
                .addProperty("R16G16_SNORM",           []{ return (int)ImageFormat::R16G16_SNORM; })
                .addProperty("R16G16_UINT",            []{ return (int)ImageFormat::R16G16_UINT; })
                .addProperty("R16G16_SINT",            []{ return (int)ImageFormat::R16G16_SINT; })
                .addProperty("R16G16_SFLOAT",          []{ return (int)ImageFormat::R16G16_SFLOAT; })

                .addProperty("R16G16B16A16_UNORM",     []{ return (int)ImageFormat::R16G16B16A16_UNORM; })
                .addProperty("R16G16B16A16_SNORM",     []{ return (int)ImageFormat::R16G16B16A16_SNORM; })
                .addProperty("R16G16B16A16_UINT",      []{ return (int)ImageFormat::R16G16B16A16_UINT; })
                .addProperty("R16G16B16A16_SINT",      []{ return (int)ImageFormat::R16G16B16A16_SINT; })
                .addProperty("R16G16B16A16_SFLOAT",    []{ return (int)ImageFormat::R16G16B16A16_SFLOAT; })

                .addProperty("R32_UINT",               []{ return (int)ImageFormat::R32_UINT; })
                .addProperty("R32_SINT",               []{ return (int)ImageFormat::R32_SINT; })
                .addProperty("R32_SFLOAT",             []{ return (int)ImageFormat::R32_SFLOAT; })

                .addProperty("R32G32_UINT",            []{ return (int)ImageFormat::R32G32_UINT; })
                .addProperty("R32G32_SINT",            []{ return (int)ImageFormat::R32G32_SINT; })
                .addProperty("R32G32_SFLOAT",          []{ return (int)ImageFormat::R32G32_SFLOAT; })

                .addProperty("R32G32B32_UINT",         []{ return (int)ImageFormat::R32G32B32_UINT; })
                .addProperty("R32G32B32_SINT",         []{ return (int)ImageFormat::R32G32B32_SINT; })
                .addProperty("R32G32B32_SFLOAT",       []{ return (int)ImageFormat::R32G32B32_SFLOAT; })

                .addProperty("R32G32B32A32_UINT",      []{ return (int)ImageFormat::R32G32B32A32_UINT; })
                .addProperty("R32G32B32A32_SINT",      []{ return (int)ImageFormat::R32G32B32A32_SINT; })
                .addProperty("R32G32B32A32_SFLOAT",    []{ return (int)ImageFormat::R32G32B32A32_SFLOAT; })

                .addProperty("D16_UNORM",              []{ return (int)ImageFormat::D16_UNORM; })
                .addProperty("D24_UNORM_S8_UINT",      []{ return (int)ImageFormat::D24_UNORM_S8_UINT; })
                .addProperty("D32_SFLOAT",             []{ return (int)ImageFormat::D32_SFLOAT; })
                .addProperty("D32_SFLOAT_S8_UINT",     []{ return (int)ImageFormat::D32_SFLOAT_S8_UINT; })

                .addProperty("BC1_UNORM",              []{ return (int)ImageFormat::BC1_UNORM; })
                .addProperty("BC1_UNORM_SRGB",         []{ return (int)ImageFormat::BC1_UNORM_SRGB; })
                .addProperty("BC2_UNORM",              []{ return (int)ImageFormat::BC2_UNORM; })
                .addProperty("BC2_UNORM_SRGB",         []{ return (int)ImageFormat::BC2_UNORM_SRGB; })
                .addProperty("BC3_UNORM",              []{ return (int)ImageFormat::BC3_UNORM; })
                .addProperty("BC3_UNORM_SRGB",         []{ return (int)ImageFormat::BC3_UNORM_SRGB; })
                .addProperty("BC4_UNORM",              []{ return (int)ImageFormat::BC4_UNORM; })
                .addProperty("BC4_SNORM",              []{ return (int)ImageFormat::BC4_SNORM; })
                .addProperty("BC5_UNORM",              []{ return (int)ImageFormat::BC5_UNORM; })
                .addProperty("BC5_SNORM",              []{ return (int)ImageFormat::BC5_SNORM; })
                .addProperty("BC6H_UFLOAT",            []{ return (int)ImageFormat::BC6H_UFLOAT; })
                .addProperty("BC6H_SFLOAT",            []{ return (int)ImageFormat::BC6H_SFLOAT; })
                .addProperty("BC7_UNORM",              []{ return (int)ImageFormat::BC7_UNORM; })
                .addProperty("BC7_UNORM_SRGB",         []{ return (int)ImageFormat::BC7_UNORM_SRGB; })
            .endNamespace()
            // BufferType
            .beginNamespace("BufferType")
                .addProperty("VERTEX",           []{ return (int)BufferType::VERTEX; })
                .addProperty("INDEX",            []{ return (int)BufferType::INDEX; })
                .addProperty("INDIRECT",         []{ return (int)BufferType::INDIRECT; })
                .addProperty("UNIFORM",          []{ return (int)BufferType::UNIFORM; })
                .addProperty("STORAGE",          []{ return (int)BufferType::STORAGE; })
                .addProperty("DEVICE_STORAGE",   []{ return (int)BufferType::DEVICE_STORAGE; })
                .addProperty("READWRITE_STORAGE",[]{ return (int)BufferType::READWRITE_STORAGE; })
                .addProperty("BUFFER_UPLOAD",    []{ return (int)BufferType::BUFFER_UPLOAD; })
                .addProperty("BUFFER_DOWNLOAD",  []{ return (int)BufferType::BUFFER_DOWNLOAD; })
                .addProperty("IMAGE_UPLOAD",     []{ return (int)BufferType::IMAGE_UPLOAD; })
                .addProperty("IMAGE_DOWNLOAD",   []{ return (int)BufferType::IMAGE_DOWNLOAD; })
            .endNamespace()
            // IndexType
            .beginNamespace("IndexType")
                .addProperty("UINT16", []{ return (int)IndexType::UINT16; })
                .addProperty("UINT32", []{ return (int)IndexType::UINT32; })
            .endNamespace()
            // DescriptorType
            .beginNamespace("DescriptorType")
                .addProperty("UNIFORM",           []{ return (int)DescriptorType::UNIFORM; })
                .addProperty("UNIFORM_DYNAMIC",   []{ return (int)DescriptorType::UNIFORM_DYNAMIC; })
                .addProperty("STORAGE",           []{ return (int)DescriptorType::STORAGE; })
                .addProperty("DEVICE_STORAGE",    []{ return (int)DescriptorType::DEVICE_STORAGE; })
                .addProperty("READWRITE_STORAGE", []{ return (int)DescriptorType::READWRITE_STORAGE; })
                .addProperty("SAMPLED_IMAGE",     []{ return (int)DescriptorType::SAMPLED_IMAGE; })
                .addProperty("SAMPLER",           []{ return (int)DescriptorType::SAMPLER; })
                .addProperty("READWRITE_IMAGE",   []{ return (int)DescriptorType::READWRITE_IMAGE; })
            .endNamespace()
            // CommandType
            .beginNamespace("CommandType")
                .addProperty("GRAPHIC",  []{ return (int)CommandType::GRAPHIC; })
                .addProperty("TRANSFER", []{ return (int)CommandType::TRANSFER; })
                .addProperty("COMPUTE",  []{ return (int)CommandType::COMPUTE; })
            .endNamespace()
            // AttributeFormat
            .beginNamespace("AttributeFormat")
                .addProperty("R32_FLOAT",          []{ return (int)AttributeFormat::R32_FLOAT; })
                .addProperty("R32G32_FLOAT",       []{ return (int)AttributeFormat::R32G32_FLOAT; })
                .addProperty("R32G32B32_FLOAT",    []{ return (int)AttributeFormat::R32G32B32_FLOAT; })
                .addProperty("R32G32B32A32_FLOAT", []{ return (int)AttributeFormat::R32G32B32A32_FLOAT; })
                .addProperty("R32_SINT",           []{ return (int)AttributeFormat::R32_SINT; })
                .addProperty("R32G32_SINT",        []{ return (int)AttributeFormat::R32G32_SINT; })
                .addProperty("R32G32B32_SINT",     []{ return (int)AttributeFormat::R32G32B32_SINT; })
                .addProperty("R32G32B32A32_SINT",  []{ return (int)AttributeFormat::R32G32B32A32_SINT; })
                .addProperty("R32_UINT",           []{ return (int)AttributeFormat::R32_UINT; })
                .addProperty("R32G32_UINT",        []{ return (int)AttributeFormat::R32G32_UINT; })
                .addProperty("R32G32B32_UINT",     []{ return (int)AttributeFormat::R32G32B32_UINT; })
                .addProperty("R32G32B32A32_UINT",  []{ return (int)AttributeFormat::R32G32B32A32_UINT; })
            .endNamespace()
            // RenderTargetType
            .beginNamespace("RenderTargetType")
                .addProperty("COLOR",          []{ return (int)RenderTargetType::COLOR; })
                .addProperty("DEPTH",          []{ return (int)RenderTargetType::DEPTH; })
                .addProperty("DEPTH_STENCIL",  []{ return (int)RenderTargetType::DEPTH_STENCIL; })
            .endNamespace()
            // CullMode
            .beginNamespace("CullMode")
                .addProperty("NONE",  []{ return (int)CullMode::NONE; })
                .addProperty("FRONT", []{ return (int)CullMode::FRONT; })
                .addProperty("BACK",  []{ return (int)CullMode::BACK; })
            .endNamespace()
            // PrimitiveTopology
            .beginNamespace("PrimitiveTopology")
                .addProperty("POINT_LIST",     []{ return (int)PrimitiveTopology::POINT_LIST; })
                .addProperty("LINE_LIST",      []{ return (int)PrimitiveTopology::LINE_LIST; })
                .addProperty("LINE_STRIP",     []{ return (int)PrimitiveTopology::LINE_STRIP; })
                .addProperty("TRIANGLE_LIST",  []{ return (int)PrimitiveTopology::TRIANGLE_LIST; })
                .addProperty("TRIANGLE_STRIP", []{ return (int)PrimitiveTopology::TRIANGLE_STRIP; })
            .endNamespace()
            // PolygonMode
            .beginNamespace("PolygonMode")
                .addProperty("FILL",      []{ return (int)PolygonMode::FILL; })
                .addProperty("WIREFRAME", []{ return (int)PolygonMode::WIREFRAME; })
            .endNamespace()
            // CompareOp
            .beginNamespace("CompareOp")
                .addProperty("NEVER",            []{ return (int)CompareOp::NEVER; })
                .addProperty("LESS",             []{ return (int)CompareOp::LESS; })
                .addProperty("EQUAL",            []{ return (int)CompareOp::EQUAL; })
                .addProperty("LESS_OR_EQUAL",    []{ return (int)CompareOp::LESS_OR_EQUAL; })
                .addProperty("GREATER",          []{ return (int)CompareOp::GREATER; })
                .addProperty("NOT_EQUAL",        []{ return (int)CompareOp::NOT_EQUAL; })
                .addProperty("GREATER_OR_EQUAL", []{ return (int)CompareOp::GREATER_OR_EQUAL; })
                .addProperty("ALWAYS",           []{ return (int)CompareOp::ALWAYS; })
            .endNamespace()
            // StencilOp
            .beginNamespace("StencilOp")
                .addProperty("KEEP",                 []{ return (int)StencilOp::KEEP; })
                .addProperty("ZERO",                 []{ return (int)StencilOp::ZERO; })
                .addProperty("REPLACE",              []{ return (int)StencilOp::REPLACE; })
                .addProperty("INCREMENT_AND_CLAMP",  []{ return (int)StencilOp::INCREMENT_AND_CLAMP; })
                .addProperty("DECREMENT_AND_CLAMP",  []{ return (int)StencilOp::DECREMENT_AND_CLAMP; })
                .addProperty("INVERT",               []{ return (int)StencilOp::INVERT; })
                .addProperty("INCREMENT_AND_WRAP",   []{ return (int)StencilOp::INCREMENT_AND_WRAP; })
                .addProperty("DECREMENT_AND_WRAP",   []{ return (int)StencilOp::DECREMENT_AND_WRAP; })
            .endNamespace()
            // BlendFactor
            .beginNamespace("BlendFactor")
                .addProperty("ZERO",                    []{ return (int)BlendFactor::ZERO; })
                .addProperty("ONE",                     []{ return (int)BlendFactor::ONE; })
                .addProperty("SRC_COLOR",               []{ return (int)BlendFactor::SRC_COLOR; })
                .addProperty("ONE_MINUS_SRC_COLOR",     []{ return (int)BlendFactor::ONE_MINUS_SRC_COLOR; })
                .addProperty("DST_COLOR",               []{ return (int)BlendFactor::DST_COLOR; })
                .addProperty("ONE_MINUS_DST_COLOR",     []{ return (int)BlendFactor::ONE_MINUS_DST_COLOR; })
                .addProperty("SRC_ALPHA",               []{ return (int)BlendFactor::SRC_ALPHA; })
                .addProperty("ONE_MINUS_SRC_ALPHA",     []{ return (int)BlendFactor::ONE_MINUS_SRC_ALPHA; })
                .addProperty("DST_ALPHA",               []{ return (int)BlendFactor::DST_ALPHA; })
                .addProperty("ONE_MINUS_DST_ALPHA",     []{ return (int)BlendFactor::ONE_MINUS_DST_ALPHA; })
                .addProperty("CONSTANT_COLOR",          []{ return (int)BlendFactor::CONSTANT_COLOR; })
                .addProperty("ONE_MINUS_CONSTANT_COLOR",[]{ return (int)BlendFactor::ONE_MINUS_CONSTANT_COLOR; })
                .addProperty("CONSTANT_ALPHA",          []{ return (int)BlendFactor::CONSTANT_ALPHA; })
                .addProperty("ONE_MINUS_CONSTANT_ALPHA",[]{ return (int)BlendFactor::ONE_MINUS_CONSTANT_ALPHA; })
                .addProperty("SRC_ALPHA_SATURATE",      []{ return (int)BlendFactor::SRC_ALPHA_SATURATE; })
                .addProperty("SRC1_COLOR",              []{ return (int)BlendFactor::SRC1_COLOR; })
                .addProperty("ONE_MINUS_SRC1_COLOR",    []{ return (int)BlendFactor::ONE_MINUS_SRC1_COLOR; })
                .addProperty("SRC1_ALPHA",              []{ return (int)BlendFactor::SRC1_ALPHA; })
                .addProperty("ONE_MINUS_SRC1_ALPHA",    []{ return (int)BlendFactor::ONE_MINUS_SRC1_ALPHA; })
            .endNamespace()
            // BlendOp
            .beginNamespace("BlendOp")
                .addProperty("ADD",              []{ return (int)BlendOp::ADD; })
                .addProperty("SUBTRACT",         []{ return (int)BlendOp::SUBTRACT; })
                .addProperty("REVERSE_SUBTRACT", []{ return (int)BlendOp::REVERSE_SUBTRACT; })
                .addProperty("MIN",              []{ return (int)BlendOp::MIN; })
                .addProperty("MAX",              []{ return (int)BlendOp::MAX; })
            .endNamespace()
            // LogicOp
            .beginNamespace("LogicOp")
                .addProperty("CLEAR",         []{ return (int)LogicOp::CLEAR; })
                .addProperty("SET",           []{ return (int)LogicOp::SET; })
                .addProperty("COPY",          []{ return (int)LogicOp::COPY; })
                .addProperty("COPY_INVERTED", []{ return (int)LogicOp::COPY_INVERTED; })
                .addProperty("NOOP",          []{ return (int)LogicOp::NOOP; })
                .addProperty("INVERT",        []{ return (int)LogicOp::INVERT; })
                .addProperty("AND",           []{ return (int)LogicOp::AND; })
                .addProperty("NAND",          []{ return (int)LogicOp::NAND; })
                .addProperty("OR",            []{ return (int)LogicOp::OR; })
                .addProperty("NOR",           []{ return (int)LogicOp::NOR; })
                .addProperty("XOR",           []{ return (int)LogicOp::XOR; })
                .addProperty("EQUIV",         []{ return (int)LogicOp::EQUIV; })
                .addProperty("AND_REVERSE",   []{ return (int)LogicOp::AND_REVERSE; })
                .addProperty("AND_INVERTED",  []{ return (int)LogicOp::AND_INVERTED; })
                .addProperty("OR_REVERSE",    []{ return (int)LogicOp::OR_REVERSE; })
                .addProperty("OR_INVERTED",   []{ return (int)LogicOp::OR_INVERTED; })
            .endNamespace()
            // ColorWriteMask
            .beginNamespace("ColorWriteMask")
                .addProperty("RED",   []{ return (int)ColorWriteMask::RED; })
                .addProperty("GREEN", []{ return (int)ColorWriteMask::GREEN; })
                .addProperty("BLUE",  []{ return (int)ColorWriteMask::BLUE; })
                .addProperty("ALPHA", []{ return (int)ColorWriteMask::ALPHA; })
                .addProperty("ALL",   []{ return (int)ColorWriteMask::ALL; })
            .endNamespace()
            // ShaderStage
            .beginNamespace("ShaderStage")
                .addProperty("ALL",      []{ return (int)ShaderStage::ALL; })
                .addProperty("VERTEX",   []{ return (int)ShaderStage::VERTEX; })
                .addProperty("FRAGMENT", []{ return (int)ShaderStage::FRAGMENT; })
                .addProperty("HULL",     []{ return (int)ShaderStage::HULL; })
                .addProperty("DOMAIN",   []{ return (int)ShaderStage::DOMAIN; })
                .addProperty("GEOMETRY", []{ return (int)ShaderStage::GEOMETRY; })
                .addProperty("COMPUTE",  []{ return (int)ShaderStage::COMPUTE; })
            .endNamespace()
            // WaitStage
            .beginNamespace("WaitStage")
                .addProperty("NONE",                                  []{ return (int)WaitStage::NONE; })
                .addProperty("PIPELINE_TOP",                          []{ return (int)WaitStage::PIPELINE_TOP; })
                .addProperty("VERTEX_INPUT",                          []{ return (int)WaitStage::VERTEX_INPUT; })
                .addProperty("VERTEX_SHADER",                         []{ return (int)WaitStage::VERTEX_SHADER; })
                .addProperty("DEPTH_STENCIL_TEST_BEFORE_FRAGMENT_SHADER", []{ return (int)WaitStage::DEPTH_STENCIL_TEST_BEFORE_FRAGMENT_SHADER; })
                .addProperty("FRAGMENT_SHADER",                       []{ return (int)WaitStage::FRAGMENT_SHADER; })
                .addProperty("DEPTH_STENCIL_TEST_AFTER_FRAGMENT_SHADER",  []{ return (int)WaitStage::DEPTH_STENCIL_TEST_AFTER_FRAGMENT_SHADER; })
                .addProperty("COLOR_OUTPUT",                          []{ return (int)WaitStage::COLOR_OUTPUT; })
                .addProperty("COMPUTE_SHADER",                        []{ return (int)WaitStage::COMPUTE_SHADER; })
                .addProperty("TRANSFER",                              []{ return (int)WaitStage::TRANSFER; })
                .addProperty("PIPELINE_BOTTOM",                       []{ return (int)WaitStage::PIPELINE_BOTTOM; })
                .addProperty("ALL_GRAPHICS",                          []{ return (int)WaitStage::ALL_GRAPHICS; })
                .addProperty("ALL_COMMANDS",                          []{ return (int)WaitStage::ALL_COMMANDS; })
                .addProperty("COPY",                                   []{ return (int)WaitStage::COPY; })
                .addProperty("RESOLV",                                 []{ return (int)WaitStage::RESOLV; })
                .addProperty("BLIT",                                   []{ return (int)WaitStage::BLIT; })
                .addProperty("CLEAR",                                  []{ return (int)WaitStage::CLEAR; })
            .endNamespace()
            // ResourceState
            .beginNamespace("ResourceState")
                .addProperty("UNDEFINED",                    []{ return (int)ResourceState::UNDEFINED; })
                .addProperty("GENERAL",                      []{ return (int)ResourceState::GENERAL; })
                .addProperty("RENDER_TARGET_COLOR",          []{ return (int)ResourceState::RENDER_TARGET_COLOR; })
                .addProperty("RENDER_TARGET_DEPTH",          []{ return (int)ResourceState::RENDER_TARGET_DEPTH; })
                .addProperty("RENDER_TARGET_DEPTH_READ",     []{ return (int)ResourceState::RENDER_TARGET_DEPTH_READ; })
                .addProperty("RENDER_TARGET_DEPTH_STENCIL",  []{ return (int)ResourceState::RENDER_TARGET_DEPTH_STENCIL; })
                .addProperty("RENDER_TARGET_DEPTH_STENCIL_READ", []{ return (int)ResourceState::RENDER_TARGET_DEPTH_STENCIL_READ; })
                .addProperty("DISPATCH_TARGET",              []{ return (int)ResourceState::DISPATCH_TARGET; })
                .addProperty("PRESENT",                      []{ return (int)ResourceState::PRESENT; })
                .addProperty("COPY_SRC",                     []{ return (int)ResourceState::COPY_SRC; })
                .addProperty("COPY_DST",                     []{ return (int)ResourceState::COPY_DST; })
                .addProperty("SHADER_READ",                  []{ return (int)ResourceState::SHADER_READ; })
                .addProperty("COMPUTE_READ",                 []{ return (int)ResourceState::COMPUTE_READ; })
                .addProperty("COMPUTE_WRITE",                []{ return (int)ResourceState::COMPUTE_WRITE; })
                .addProperty("INDIRECT_DRAW",                []{ return (int)ResourceState::INDIRECT_DRAW; })
                .addProperty("VERTEX_INPUT",                 []{ return (int)ResourceState::VERTEX_INPUT; })
                .addProperty("UNIFORM",                      []{ return (int)ResourceState::UNIFORM; })
            .endNamespace()
            // MSAA
            .beginNamespace("MSAA")
                .addProperty("NONE", []{ return (int)MSAA::NONE; })
                .addProperty("X2",   []{ return (int)MSAA::X2; })
                .addProperty("X4",   []{ return (int)MSAA::X4; })
                .addProperty("X8",   []{ return (int)MSAA::X8; })
                .addProperty("X16",  []{ return (int)MSAA::X16; })
                .addProperty("X32",  []{ return (int)MSAA::X32; })
                .addProperty("X64",  []{ return (int)MSAA::X64; })
            .endNamespace()
            .beginNamespace("PresentMode")
                .addProperty("IMMEDIATE", []{ return (int)PresentMode::IMMEDIATE; })
                .addProperty("VSYNC",     []{ return (int)PresentMode::VSYNC; })
            .endNamespace()
            // PipelineType
            .beginNamespace("PipelineType")
                .addProperty("GRAPHIC", []{ return (int)PipelineType::GRAPHIC; })
                .addProperty("COMPUTE", []{ return (int)PipelineType::COMPUTE; })
            .endNamespace()
            // SemaphoreType
            .beginNamespace("SemaphoreType")
                .addProperty("BINARY",   []{ return (int)SemaphoreType::BINARY; })
                .addProperty("TIMELINE", []{ return (int)SemaphoreType::TIMELINE; })
            .endNamespace()
        .endNamespace();
    }

}